# LLM Configuration
llm:
  provider: "openai"  # Default provider (openai, anthropic, deepseek)
  models:
    openai: "gpt-4-turbo-preview"
    anthropic: "claude-3-sonnet-20240229"
    deepseek: "deepseek-chat"
  temperature: 0.7
  max_tokens: 4000
  timeout: 60
  max_retries: 3
  retry_delay: 1

# Application Settings
app:
  debug: true
  log_level: "INFO"
  cache_dir: "cache"
  max_upload_size: 10  # MB
  supported_formats:
    - "pdf"
    - "docx"
    - "txt"
    - "html"

# Standards Configuration
standards:
  default_frameworks:
    - "GRI"
    - "SASB"
    - "TCFD"
  cache_enabled: true
  cache_ttl: 86400  # 24 hours in seconds

# Analysis Settings
analysis:
  max_documents: 10
  max_tokens_per_document: 100000
  chunk_size: 1000
  chunk_overlap: 200
  similarity_threshold: 0.7
  max_results: 100

# UI Settings
ui:
  theme: "light"
  primary_color: "#1E88E5"
  secondary_color: "#43A047"
  accent_color: "#FFA000"
  font_family: "Inter"
  max_display_results: 50
  show_confidence: true
  show_metrics: true 